# Generated by Django 5.2.8 on 2026-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
