# Generated by Django 5.2.8 on 2026-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
