# Generated by Django 5.2.8 on 2026-04-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
