# Generated by Django 5.2.8 on 2026-01-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_options_remove_address_house_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
