# Generated by Django 5.2.8 on 2026-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_original_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='original_subtotal',
        ),
        migrations.AddField(
            model_name='order',
            name='original_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
