# Generated by Django 5.2.8 on 2026-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
