# Generated by Django 5.2.8 on 2026-04-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_offer_percentage_product_offer_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
